import type { OAuthHelpers } from "@cloudflare/workers-oauth-provider";

/**
 * Worker bindings. Runtime types (KVNamespace, DurableObjectNamespace, ...)
 * and the base `Cloudflare.Env` namespace come from `worker-configuration.d.ts`,
 * which is generated by `npm run types` (wrangler types) — run that once
 * after `npm install` and again whenever wrangler.toml bindings change.
 */
export interface Env extends Cloudflare.Env {
  // Bindings declared in wrangler.toml (OAUTH_KV, MCP_OBJECT) are already
  // typed on the generated Cloudflare.Env — only add what wrangler can't
  // know about, i.e. everything managed in the dashboard under
  // Settings → Variables and Secrets:

  // --- plain text variables (dashboard-managed, keep_vars = true) ---
  ALLOWED_GITHUB_USER: string;
  INTERNAL_SERVICE_URL: string;

  // --- secrets (dashboard-managed) ---
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  COOKIE_ENCRYPTION_KEY: string;
  ACCESS_CLIENT_ID: string;
  ACCESS_CLIENT_SECRET: string;

  /**
   * Injected automatically by OAuthProvider into the default handler's env.
   * Not a wrangler binding — do not add it to wrangler.toml.
   */
  OAUTH_PROVIDER: OAuthHelpers;
}

/**
 * Everything above except OAUTH_PROVIDER is dashboard-managed and therefore
 * can be missing on a fresh deploy. Callers use this to fail with a clear
 * message instead of a confusing downstream error.
 */
export function missingConfig(env: Env): string[] {
  return (
    [
      "ALLOWED_GITHUB_USER",
      "INTERNAL_SERVICE_URL",
      "GITHUB_CLIENT_ID",
      "GITHUB_CLIENT_SECRET",
      "COOKIE_ENCRYPTION_KEY",
      "ACCESS_CLIENT_ID",
      "ACCESS_CLIENT_SECRET",
    ] as const
  ).filter((key) => !env[key]);
}

/**
 * Per-grant properties stored by workers-oauth-provider when the OAuth flow
 * completes (github-handler.ts), and made available to every MCP session as
 * `this.props` inside the Durable Object agent (index.ts).
 */
export type Props = {
  login: string;
  name: string;
  accessToken: string;
};
